import os
import subprocess
from pathlib import Path
from .logger import setup_logger

logger = setup_logger("cert_manager")

class CertManager:
    def __init__(self):
        # Standard Mitmproxy cert location
        self.cert_path = Path.home() / ".mitmproxy" / "mitmproxy-ca-cert.cer"

    def ensure_cert_installed(self):
        if not self.cert_path.exists():
            logger.info("Certificate not found. It will be generated by Mitmproxy on first run.")
            return

        logger.info(f"Checking certificate installation: {self.cert_path}")
        
        try:
            # Use certutil to add to current user's Root store
            # -f: force, -user: current user, -addstore "Root"
            cmd = ["certutil", "-user", "-addstore", "Root", str(self.cert_path)]
            subprocess.run(cmd, check=True, capture_output=True)
            logger.info("Certificate registered successfully.")
        except subprocess.CalledProcessError as e:
            logger.error(f"Failed to register certificate: {e}")